### ISSUE TITLE
Unable to evaluate constant expression

### ISSUE THREAD

**Issue by Grinshpon** [zenith391/didot#2]
This is on Windows 10 with Zig 0.7.1

When trying to build the basic example, I get a compiler error that says:

```
.\deps\didot\build.zig:35:32: error: unable to evaluate constant expression
            const target = step.target.toTarget().os.tag;
                               ^
.\build.zig:18:28: note: called from here
  try engine.addEngineToExe(exe, .{
                           ^
.\build.zig:4:33: note: called from here
pub fn build(b: *Builder) !void {
                                ^
.\deps\didot\build.zig:35:48: note: referenced here
            const target = step.target.toTarget().os.tag;
                                               ^
.\build.zig:18:3: note: referenced here
  try engine.addEngineToExe(exe, .{
  ^
```

The build file is the default zig build file with the code from the [How to use](https://github.com/zenith391/didot#how-to-use) section of the readme pasted into it (with the strings changed to the proper directory), and the source file is the example code from the readme as well.

**Comment by zenith391** [comment]
By the way the code of the example code in the README got edited to fit with the new component system.
